#ifndef Crawl_ABSTRACT_LEVEL_GLOBAL_H
#define Crawl_ABSTRACT_LEVEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CRAWL_ABSTRACT_LEVEL_LIBRARY)
#  define CRAWL_ABSTRACT_LEVEL_EXPORT Q_DECL_EXPORT
#else
#  define CRAWL_ABSTRACT_LEVEL_EXPORT Q_DECL_IMPORT
#endif

#endif // Crawl_ABSTRACT_LEVEL_GLOBAL_H
