#ifndef SERVERPROTOCOL_GLOBAL_H
#define SERVERPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERPROTOCOL_LIBRARY)
#  define SERVERPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERPROTOCOL_GLOBAL_H
